### ISSUE TITLE
Missing examples?

### ISSUE THREAD

**Issue by miketaylr** [WICG/explicit-javascript-compile-hints-file-based#7]
It would be nice if there were an example or two in the intro (or elsewhere) that showed how a user might use this:

Something like the `//# eagerCompilation=all` comment in the explainer (presumably `all` is the only currently supported value today?)

**Comment by marjakh** [comment]
I added an example here: https://github.com/WICG/explicit-javascript-compile-hints-file-based/blob/main/README.md#introduction ; does that answer your question?

**Comment by miketaylr** [comment]
That's helpful! If you put that in the draft spec that would also be cool. 😸
